/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectDocsRouteImport } from './routes/project-docs'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectDocsIndexRouteImport } from './routes/project-docs.index'
import { Route as ProjectDocsDocIdRouteImport } from './routes/project-docs.$docId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'

const ProjectDocsRoute = ProjectDocsRouteImport.update({
  id: '/project-docs',
  path: '/project-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDocsIndexRoute = ProjectDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectDocsRoute,
} as any)
const ProjectDocsDocIdRoute = ProjectDocsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => ProjectDocsRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/project-docs': typeof ProjectDocsRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project-docs/$docId': typeof ProjectDocsDocIdRoute
  '/project-docs/': typeof ProjectDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project-docs/$docId': typeof ProjectDocsDocIdRoute
  '/project-docs': typeof ProjectDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changes': typeof ChangesRoute
  '/docs': typeof DocsRoute
  '/project-docs': typeof ProjectDocsRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/project-docs/$docId': typeof ProjectDocsDocIdRoute
  '/project-docs/': typeof ProjectDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changes'
    | '/docs'
    | '/project-docs'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/project-docs/$docId'
    | '/project-docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changes'
    | '/docs'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/project-docs/$docId'
    | '/project-docs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changes'
    | '/docs'
    | '/project-docs'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/project-docs/$docId'
    | '/project-docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangesRoute: typeof ChangesRoute
  DocsRoute: typeof DocsRoute
  ProjectDocsRoute: typeof ProjectDocsRouteWithChildren
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project-docs': {
      id: '/project-docs'
      path: '/project-docs'
      fullPath: '/project-docs'
      preLoaderRoute: typeof ProjectDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-docs/': {
      id: '/project-docs/'
      path: '/'
      fullPath: '/project-docs/'
      preLoaderRoute: typeof ProjectDocsIndexRouteImport
      parentRoute: typeof ProjectDocsRoute
    }
    '/project-docs/$docId': {
      id: '/project-docs/$docId'
      path: '/$docId'
      fullPath: '/project-docs/$docId'
      preLoaderRoute: typeof ProjectDocsDocIdRouteImport
      parentRoute: typeof ProjectDocsRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectDocsRouteChildren {
  ProjectDocsDocIdRoute: typeof ProjectDocsDocIdRoute
  ProjectDocsIndexRoute: typeof ProjectDocsIndexRoute
}

const ProjectDocsRouteChildren: ProjectDocsRouteChildren = {
  ProjectDocsDocIdRoute: ProjectDocsDocIdRoute,
  ProjectDocsIndexRoute: ProjectDocsIndexRoute,
}

const ProjectDocsRouteWithChildren = ProjectDocsRoute._addFileChildren(
  ProjectDocsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangesRoute: ChangesRoute,
  DocsRoute: DocsRoute,
  ProjectDocsRoute: ProjectDocsRouteWithChildren,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
